site_title = "robot papers"
limit_days = 7
cache_url = "https://liujy25.github.io/robot-papers/cache.json"

[[sources]]
limit = 150
category = "cs.CL"
title = "Computation and Language"

[[sources]]
limit = 150
category = "cs.CV"
title = "Computer Vision and Pattern Recognition"

[[sources]]
limit = 150
category = "cs.IR"
title = "Information Retrieval"

[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 150
category = "cs.MM"
title = "Multimedia"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
