site_title = "Robot Papers"
limit_days = 7
cache_url = "https://liujy25.github.io/robot-papers/cache.json"

[[sources]]
limit = 150
category = "cs.RO"
title = "Robotics"

[[sources]]
limit = 150
category = "cs.CV"
title = "Computer Vision and Pattern Recognition"

[[sources]]
limit = 150
category = "cs.AI"
title = "Artificial Intelligence"

[[sources]]
limit = 150
category = "cs.GR"
title = "Graphics"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
